[hardware_computing] Add session content
security-summer-school/hardware-sec pull request #11
Opened 2023-03-23 09:48 UTC by cristian-vijelie

2023-06-25 15:09 UTC, StefanJum requested changes
This looks really nice @cristian-vijelie, see the few comments.
Also, will the `hardware-isolation` directory be used for something else? If not we should just remove it.

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/README.md
> +There are other less-known mechanisms for ensuring memory isolation, through which we will go this session: segments, privilege rings, memory protection keys.
```suggestion
You have encountered (hopefully) the main protection mechanism that the hardware uses to ensure memory isolation: [pages](...).
There are other less-known mechanisms for ensuring memory isolation, through which we will go this session: [segments](...), [privilege rings](...), [memory protection keys](...).
```
Leave links to some relevant pages about the topics.

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/README.md
> +This meant that the maximum memory size that could be used, with **flat memory addressing** model, was 64KB.
```suggestion
This meant that the maximum memory size that could be used, with **flat memory addressing** model, was 64KB (2^16).
```

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/README.md
> +The way the addresses were calculated was the following:
```suggestion
The way the addresses were calculated was the following:

```
Leave blanc lines before and after snippets.

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/README.md
> +This led to a new memory maximum of almost 1MB, which was tought to be enough.
```suggestion

This led to a new memory maximum of almost 1MB, which was tought to be enough.
```

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/README.md
> +you could barely reach 4GB of RAM.
```suggestion
You could barely reach 4GB of RAM.
```

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/README.md
> +But first, something about privilege levels, also known as privilege rings.
```suggestion
But first, something about privilege levels, also known as **privilege rings**.
```

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/activities/read-gdt/public/Makefile
> +	make -C /home/cristi/WSL2-Linux-Kernel M=$(shell pwd) clean
```suggestion
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
```

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/activities/read-gdt/public/Makefile
> +	make -C /home/cristi/WSL2-Linux-Kernel M=$(shell pwd) clean
Besides this, ask people somewhere in the session to install the kernel header files.
```console
$ apt-cache search linux-headers-`uname -r`
$ sudo apt install linux-headers.....
```

Also ask them to run this from inside a virtual machine.

2023-06-25 15:09 UTC, StefanJum commented on hardware-memory-isolation/README.md
> +Go to the [`read-gdt`](./activities/read-gdt/) folder.
See the comments on the `Makefile`.

2023-06-26 04:28 UTC, teodutu requested changes
I like this session. There are places where it could use some improvements. See my comments.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +Another role of the hardware, besides computing, is to provide isolation, mainly between different software components.
This statement is dubious. What do you mean by "isolation between software components"? The hardware isn't aware of the software.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +You get to write a small hypervisor.
```suggestion
You'll get to write a small hypervisor.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +At the beginning of time, x86 CPUs had only 16-bits registers.
```suggestion
At the beginning of time, x86 CPUs only had 16-bit registers.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +It was thought that this memory is enough, until it wasn't enough.
```suggestion
It was thought that this amount of memory is enough, until it wasn't enough.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +The way the addresses were calculated was the following:
```suggestion
The way the addresses were calculated was the following:

```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +This led to a new memory maximum of almost 1MB, which was tought to be enough.
```suggestion

This led to a new memory maximum of almost 1MB, which was thought to be enough.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +addr = SEGMENT_REGISTER * 0x10 + OFFSET_REGISTER
```suggestion
address = SEGMENT_REGISTER * 0x10 + OFFSET_REGISTER
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +you could barely reach 4GB of RAM.
```suggestion
You could barely reach 4GB of RAM.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +The GDT is a system table, that contains descriptors of memory zones: where it starts, where it ends, how it grows, is it readable, writeable, executable, who can access it.
```suggestion
The GDT is a system table, that contains descriptors of memory zones: where they start, where they end, how they grow, whether they are readable, writeable, executable, who can access them
```

Also, "system table" may mislead some to believe it's a software data structure.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +    * L - Long-mode code: if 1, the segment is a 64-bit code one
Use **bold** when you introduce a field as shown below to make it more visible:
```
* **Base**: the address at which the segment begins
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
Shouldn't this be renamed `index.md` to be rendered on https://security-summer-school.github.io/ ?

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +The **protected mode** was born.
You should say that the real mode is still used for a short while at boot time, for compatibility.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +    * E: Executable; if 0, the segment is a data one; if 1, the segment is a code one
```suggestion
    * E: Executable; 1 if executable, 0 otherwise
```
Keep things shorter, there's a lot of information to digest in this list.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +As complicated as it looks, The GDT did its job of enforcing some memory protection, hence a CPU with a GDT and 32-bit addresses is in the **Protected Mode**.
```suggestion
As complicated as it looks, The GDT did its job of enforcing some memory protection, hence a CPU with a GDT and 32-bit addresses is operating in **Protected Mode**.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +Yes?
```suggestion
Yes.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +You may have heard about kernel-space and user-space.
```suggestion
You should have heard about kernel-space and user-space.
```
And add this as a prerequisite for this session. It becomes pointless otherwise.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +Let's break each field down:
It may be useful to show some code at this point:
- https://elixir.bootlin.com/linux/v6.3.9/source/arch/x86/kernel/cpu/common.c#L205
- https://elixir.bootlin.com/linux/v6.3.9/source/arch/x86/include/asm/segment.h#L59

Our [OS Internals class](https://linux-kernel-labs.github.io/refs/heads/master/lectures/address-space.html#segmentation-in-linux) covers this topic quite nicely. You might want to draw some inspiration from here.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +That memory zone is part of a segment, or page, as we will see later, that belongs to either kernel or user.
```suggestion
That memory zone is part of a segment and a page, as we will see later, that belongs to either kernel or user.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +Go to the [`read-gdt`](./activities/read-gdt/) folder.
Depending on the students' kernel programming experience, this may be a bit overwhelming. Provide some contexts and a walkthrough of the code first.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +Unlike segments, that can be of any size, pages have fixed sizes: 4KB.
This is actually configurable. You ought to mention this.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +To do this it will call `mprotect` on that area.
```suggestion
To do this, it will call `mprotect()` on that area.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +What will happen behind the scenes will be that the OS will change permissions for each page that is part of the memory area, then it will flush the TLB.
The TLB appears out of nowhere here. Add the concept of MMU + TLB as a prerequisite altogether, together with paging in general.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +As a solution, Intel proposed the MPK set of instructions, that can quickly change permissions for an area of memory of any size.
```suggestion
As a solution, Intel proposed the `MPK` set of instructions, that can quickly change permissions for an area of memory of any size.
```

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +It allocates a `protection domain` with read permissions, then adds the page to that protection domain.
```suggestion
It allocates a _protection domain_ with read permissions, then adds the page to that protection domain.
```
Only use backticks for code.

2023-06-26 04:28 UTC, teodutu commented on hardware-memory-isolation/README.md
> +Let's take a practical example:
This is too much text. Try to make a practical example out of this somehow (hopefully via a tutorial that modifies the `PKRU`). You can draw some inspiration from [here](https://charlycst.github.io/posts/mpk/).

2023-06-27 14:08 UTC, cristian-vijelie commented on hardware-memory-isolation/README.md
> +Another role of the hardware, besides computing, is to provide isolation, mainly between different software components.
it isn't aware of processes, but it is aware of kernel vs user software

2023-06-27 14:16 UTC, cristian-vijelie commented on hardware-memory-isolation/README.md
> +That memory zone is part of a segment, or page, as we will see later, that belongs to either kernel or user.
here it's a small issue: you can have a user page in both user segment and kernel segment, because today all segments cover the entiore space address

2023-06-27 16:50 UTC, mariasfiraiala requested changes
Thanks @cristian-vijelie, this looks nice. See my comments below.

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +Another role of the hardware, besides computing, is to provide isolation, mainly between different software components.
If you choose to go with this statement, after @teodutu's comments, please rephrase it, just a bit.
```suggestion
Besides computing, another role of the hardware, is to provide isolation, mainly between different software components.
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +There are other less-known mechanisms for ensuring memory isolation, through which we will go this session: segments, privilege rings, memory protection keys.
```suggestion
There are other less-known mechanisms for ensuring memory isolation, through which we will go during this session: segments, privilege rings, memory protection keys.
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +How can you do this?
```suggestion
How can this be achieved?
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +The first answer that the CPU designers had is called **segmentation**.
```suggestion
The first answer that the CPU designers came up with was called **segmentation**.
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +Segmentation is the x86 CPU feature that allows assigning permissions and ownership to a certain memory zone, using segments.
Add a bit more detail as to what segments represent. They can be easily confused with pages by novices.

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +It didn't enforce any permissions on the memory zone, or ownership, because there was no user and kernel separation.
```suggestion
It didn't enforce any permissions on the memory zone, or ownership, because there was no user-kernel separation.
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +Fortunately, in modern systems, **Base** and **Limit** are ignored.
```suggestion

Fortunately, in modern systems, **Base** and **Limit** are ignored.
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +Does that mean that the entire address space is in both code and data segments?
```suggestion
Does that mean that the entire address space is in both the code and data segments?
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +That memory zone is part of a segment / a page, as we will see later, that belongs to either kernel or user.
```suggestion
That memory zone is part of a segment / a page, as we will see later, that belongs to either the kernel or the user.
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +We have the following scenario:
```suggestion
Let's consider the following scenario:
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +A classical example of `use-after-free`.
```suggestion
A classic example of `use-after-free`.
```

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +The shadow stack places a copy of the return address in a separate memory zone, that can be accessed using only some special instructions.
You might want to show how this can be achieved hardware wise. There are already some compiler enforced mechanism similar to this, that were however, deemed not as efficient (ShadowCallStack, SafeStack).

2023-06-27 16:50 UTC, mariasfiraiala commented on hardware-memory-isolation/README.md
> +The main idea behind some attacks is to chain small pieces of code (gadgets), in order to call a system function, usually, in a certain way.
>  usually, in a certain way

This is quite vague

2023-06-28 02:25 UTC, teodutu commented on hardware-memory-isolation/README.md
> +Another role of the hardware, besides computing, is to provide isolation, mainly between different software components.
OK, I get it now, but you need to reword this to reflect your reply. Otherwise, it's unclear.

2023-06-28 02:44 UTC, teodutu commented on hardware-memory-isolation/README.md
> +The main idea behind some attacks is to chain small pieces of code (gadgets), in order to call a system function, usually, in a certain way.
I'd suggest referring to the [Binary track](https://security-summer-school.github.io/binary/return-oriented-programming/) for this since it's beyond the scope of the Hardware track.

2025-06-26 11:58 UTC, closed without merging